### PR TITLE
Basic ObjectRelation support

### PR DESCRIPTION
**Pull request by nspyke**
Adds very basic support for ObjectRelation field types

### CODE REVIEW

**Comment by MarioBlazek** [comment]
Please rename ObjectRelation to Relation and add some tests. Except that +1.

**Comment by MarioBlazek** [comment]
ping @pspanja

**Comment by nspyke** [comment]
@MarioBlazek Updated as requested

**Review by pspanja — APPROVED** [review]
Nice, thanks @nspyke!

**Pull request merged**
